### PR TITLE
Accordion svg

### PR DESCRIPTION
**Pull request by peter-mouland**
> v6.0.0-alpha: merging this goes into the v6 branch, not master.

## What this PR resolves
The chevron in the 'extended' accordion was too light.

Rather than creating a `dark-grey-chevron`, we have created a new `chevron` which is green by default.  This chevron, used inline, can then have its colour changed using CSS.

We have kept the old chevrons so as not to potentially break more apps.  However, because the html has now changed for accordions, this is still a breaking change.

## Screenshot before PR (if applicable):

screen shot 2016-02-18 at 15 02 41

## Screenshot after PR:

screen shot 2016-02-18 at 15 48 39

### CODE REVIEW

**Comment by bentidy** [comment]
i think the chevrons next to the accordion are slightly out of alignment, i think they are meant to be aligned to the middle of the text no the very top / very bottom ?

**Comment by peter-mouland** [comment]
good spot - will fix

**Comment by peter-mouland** [comment]
fixed the chevron alignment

**Comment by peter-mouland** [comment]
closing this PR to sort this git history...

**Comment by peter-mouland** [comment]
closing to sort the history

**Pull request closed without merging**
