### PR TITLE
add normalize.css

### PR DESCRIPTION
**Pull request by peter-mouland**

### CODE REVIEW

**Comment by peter-mouland** [comment]
do we also want to do things like : 

 - set `margin:0` for all h tags
 - make the `.now-link` default for all `a` tags

What other resets or peoples apps setting?

**Comment by rogerfranklin2** [comment]
How much of normalize.css do we actually need, we don't support old IE's etc so don't need more than half of the things that it pulls in

Does this qualify as a polyfill so each client should bring it in if they want to support it?

**Comment by peter-mouland** [comment]
it is a sort of polyfill - but i think its a good place to start as an effort to get all our apps looking the same. (its only 8k before minification).  If people feel it's not needed then cool.

What things would should we add to 'resets'?
 - `h1,h2,h3,h4,h5,h6{ margin:0}`
 - make the .now-link default for all a tags

anything else?

**Comment by peter-mouland** [comment]
In addition here are some useful ideas i pinched from html5Doctor:
```CSS
html, body,
h1, h2, h3, h4, h5, h6, p {
    margin:0;
}

nav ul {
    list-style:none;
}

del {
    text-decoration: line-through;
}

input, select {
    vertical-align:middle;
}
```

**Comment by NowTV-Assurance** [comment]
:+1: @tomatau @philtoms

**Comment by alexflorisca** [comment]
:+1:

**Comment by bentidy** [comment]
:+1: @rogerfranklin2

**Pull request merged**
