### PR TITLE
PT: Update button to match UI design

### LINKED ISSUE #116: Buttons do not match the UI Designs
## Current Implementation
screen shot 2016-02-26 at 12 21 26

## UI Designs
screen shot 2016-02-26 at 12 21 33

@peterthompson

### PR DESCRIPTION
**Pull request by nowarkdev**
Fixes #116 Buttons do not match the UI Designs

## What this PR resolves
- Buttons will match UI design

## Screenshot before PR:
screen shot 2016-02-26 at 12 56 08

## Screenshot after PR:
screen shot 2016-02-26 at 12 55 19

@peterthompson

### CODE REVIEW

**Comment by peter-mouland** [comment]
if this ok with jamie/vick :+1:

**Comment by bentidy** [comment]
On mobile the buttons should be 56px in height according to Zeplin. If we could make this change as part of this PR then we'd give this a :+1: 

@ldabiralai @nwc1991

**Comment by nowarkdev** [comment]
Good spot! Thanks guys, made that change.

**Comment by jamiehgreen** [comment]
this is still in review at the moment.. will update Zeplin on monday

**Comment by peterthompson** [comment]
Do not merge yet, needs updating.

Following chat with Jamie, desktop buttons should have a height of 50px, mobile 44px.

**Comment by andrewmerrell** [comment]
We are close to merging the two repo's (styleguide + toolkit). 
Once they are merged, could you redo this PR onto the new 'web-toolkit'?

**Pull request closed without merging**
