### PR TITLE
JM|PD: Added font stylings (originally in toolkit)

### PR DESCRIPTION
**Pull request by nowarkdev**
@james-maher , @PLAGR34GTT 
Font styling copied/moved from react-toolkit - looking to remove it from toolkit.

### CODE REVIEW

**Comment by ldabiralai** [comment]
I know this is only small and a bit pedantic, but seeing as it's sass, could we remove the semicolons from the end of the lines?

**Comment by peter-mouland** [comment]
:+1:

**Comment by ldabiralai** [comment]
:+1:

**Comment by nowarkdev** [comment]
Closed by #40 @ariley90

**Pull request closed without merging**
