### PR TITLE
Component updates

### PR DESCRIPTION
**Pull request by nowarkdev**
* Adding valid and error icons for text inputs
* Tweaks to checkboxes, radio buttons
* Header component styles

### CODE REVIEW

**Comment by peter-mouland** [comment]
could you do a rebase from master (to remove dist which will make the PR easier to read) and then also add screenshots to highlight the difference... maybe 'before' and 'after' shots to make it super easy to review?

**Comment by peter-mouland** [comment]
seems to be missing icons
screen shot 2016-01-20 at 12 12 59

**Comment by nowarkdev** [comment]
@krow-ten @peter-mouland There is a placeholder style (".header-icon") for an icon but there isn't an icon pack at the moment. It's something that can be added independently.

**Comment by peter-mouland** [comment]
it's hard to give this a thumbs up when the header component is incomplete.

If the other components were in separate PR's we could OK them individually, as it is :-1:

**Comment by alexjfno1** [comment]
Could something like that be marked as WIP?

**Comment by rogerfranklin2** [comment]
View comments on slack channel #nowtv-toolkit

**Comment by rogerfranklin2** [comment]
Looks good :+1: 

I think the myaccount guys are working on the react version with the animation

**Comment by alexjfno1** [comment]
@rogerfranklin2 I thought you guys had done it already?

**Comment by nowarkdev** [comment]
@benstokoe: Looks good 👍

**Comment by peter-mouland** [comment]
cool - i understand now the text has changed to lorem ipsum :+1:

**Pull request merged**
