### PR TITLE
BS|RH: Update the colours according to new stylesheet

### PR DESCRIPTION
**Pull request by nowarkdev**
2.0 colours!

### CODE REVIEW

**Comment by andrewmerrell** [comment]
FYI, we did discuss this on the react toolkit and switched from that method to colour names.

https://davidwalsh.name/sass-color-variables-dont-suck

**Comment by nowarkdev** [comment]
React toolkit is using mainly the same scheme we have https://github.com/sky-uk/nowtv-react-toolkit/blob/master/src/_colours.sass

**Comment by peter-mouland** [comment]
personally, i disagree with DWB as pickled-bluewood doesnt tell me anything neither do i know the difference between $silver-chalice and $scorpion. i'd prefer the colour

**Comment by peter-mouland** [comment]
who did this PR?

**Comment by nowarkdev** [comment]
@benstokoe and Rob Howe

**Comment by bentidy** [comment]
:+1:  But what David Walsh is describing is different to the way that we have it implemented, the way that the navigation does it is the way.

We have a mapping from red to monza.  then we can change the monza part but in your apps you will always just use the red variable.

But thats a bit off topic

**Pull request merged**
