### PR TITLE
add classes to allow more flexible markup for headings

### PR DESCRIPTION
**Pull request by peter-mouland**

### CODE REVIEW

**Comment by bentidy** [comment]
I'm not sure if it makes sense to do this. This makes it easier for people to not use headings when they want a heading, which I understand.

But for accessibility should we not be using h(1,2,3s) to keep a structural hierarchy in the page?

@ldabiralai

**Comment by peter-mouland** [comment]
yeah, they should be using h's.  The styleguide should not be dictating which `h` must be used as this depends on the other elements on the page.  This is especially true when headers are hidden from visual reason and used for screen-readers.  

For example, we need to make the h2 look like a h1

**Comment by nowarkdev** [comment]
@ariley90 :+1:

**Comment by ldabiralai** [comment]
Just one last question.

If you guys feel that there should be hierarchy for screen readers, does that not also suggestion there should also be a visual hierarchy for visual users?

**Comment by peter-mouland** [comment]
yeah.

**Comment by ldabiralai** [comment]
So then why should this change be introduced?

**Comment by peter-mouland** [comment]
The hierarchy is one part of it. We spoke about the design of the page being another.  

We have page with h1 and h2.  There is also some bold text.  As far as the designer is concerned there is no 'h3'.  We, as developers, want to code up a bold piece of text as a h3.

We do not want to have to code over the style-guide to use our own font-size and breakpoints as this is duplication.  Hacking the style-guide makes our own app more complex and brittle.

**Comment by peter-mouland** [comment]
We have now updated the classnames to match the Design Guide (from Zeplin) based on the conversation earlier.

**Comment by alexflorisca** [comment]
Yeah I think it's basically just a nice way to overwrite styles - only IF and when you need to. You can do this anyway in your app manually, or as I see it with these classes. Should still be devs responsibility to keep visual hierarchy but not all h3s were made equal by designers in every app. 

:+1: but use wisely :p

**Pull request merged**
