### PR TITLE
add default styles to extended accordion

### PR DESCRIPTION
**Pull request by peter-mouland**
The purpose of this is to ensure that the style of the 'extended' accordion is standard across sites.

Before this PR, the extended accordion was styled within the docs css as an example.  I think this css should be rolled into the style-guide so all sites with the 'extended' accordion can benefit.

### CODE REVIEW

**Comment by rogerfranklin2** [comment]
I thought the extended accordion was used for anytime you don't want the FAQ style accordion so it wouldn't really have a style just provide the classes and the open/close functionality that you need to style?

**Comment by peter-mouland** [comment]
I've seen this style of accordion in the showcase in multiple apps, so thought it made sense to make it an 'official' style

**Comment by alexflorisca** [comment]
It's all good with me but you've also refactored the typography section by the looks of it. Hard to give a thumbs up without checking the visuals - the heroku pr apps seem to be broken - mind fixing this?

**Comment by peter-mouland** [comment]
good spot. have removed that now

**Comment by peter-mouland** [comment]
spoke with @rogerfranklin2 and as these styles are used in multiple apps - we're happy to merge

**Comment by NowTV-Assurance** [comment]
FWIW this changes the classnames used for styles and so the toolkit needs to be updated too.

**Pull request merged**
