### PR TITLE
RF|NC: Adding trigger class and display-inline block on trigger

### PR DESCRIPTION
**Pull request by bentidy**
fixes: problem with the react toolkit making the whole row which the trigger is on clickable

### CODE REVIEW

**Comment by johnsibly** [comment]
:+1:

**Comment by nowarkdev** [comment]
:+1:  @PLAGR34GTT

**Comment by peter-mouland** [comment]
RF | NC could you tag your names in this PR please?

**Comment by peter-mouland** [comment]
This 'triggers', (just like for the 'notification' and 'tip' components) aren't really a part of this style of this component. i.e. we currently only demo the component itself, the trigger could be a now-button or some text.  

To me, this is a problem that should be fixed in the react-toolkit docs

**Comment by bentidy** [comment]
Ok no problem, made a new PR

**Pull request merged**
