### PR TITLE
RP, JM: Tweak padding on headers

### PR DESCRIPTION
**Pull request by nowarkdev**
@roryp2 @james-maher

### CODE REVIEW

**Comment by peter-mouland** [comment]
could you help us clear some other PR's by commenting on them?
Once we get through the backlog, the demo app for this PR can be built making it easier to review.  In the mean-time do you have a before and after shot to allow us to see the difference you have made?

**Comment by alexflorisca** [comment]
:+1:

**Comment by bentidy** [comment]
For ```.header-heading``` should we just use ```margin: 10px 0 15px``` as we already have a margin set on it?

Also, how come the subheading has been removed from the doc example?

@ldabiralai @nwc1991

**Comment by peter-mouland** [comment]
agree with @ldabiralai @nwc1991

**Comment by nowarkdev** [comment]
@ldabiralai @nwc1991 @peter-mouland If you use margin for the .header-heading and you don't have a sub-heading then you won't have the background colour and it looks bad, I removed the sub-heading from one of the examples to show what it now looks like, as we have designs with no sub-heading.

@roryp2

**Comment by peter-mouland** [comment]
@roryp2 cool - thanks for the explanation!!
:+1:

**Pull request merged**
