### PR TITLE
3-Column Layout CSS Component

### PR DESCRIPTION
**Pull request by peter-mouland**

### CODE REVIEW

**Comment by bentidy** [comment]
:-1:  It looks like this has been copied from our project and is now out of date. This does not work for tablet users so we have changed it. We have also simplified it a bit following discussions with the designers

A side note is that we haven't decided to move to BEM yet so not sure why you converted our stuff from SMACSS to BEM, this should wait until we have had the discussion.

@rogerfranklin2 @bdo

**Comment by NowTV-Assurance** [comment]
currently the style-guide doesn't follow a single convention, so rather than block all future PR's we have submitted something that works.  Class names are easy to update.

This is a starting point, If you know of a bug, please contribute and improve this code!!  There is no point 3 teams bug-fixxing and building the same thing in 3 different ways.

We aim for improvements, not perfection, otherwise nothing will ever ben submitted.  For me, as this is a massive improvement (over what the style-guide has previously i.e. nothing), lets get it in, then if there are bugs, lets improve it.

**Comment by peter-mouland** [comment]
currently the style-guide doesn't follow a single convention, so rather than block all future PR's we have submitted something that works. Class names are easy to update.

This is a starting point, If you know of a bug, please contribute and improve this code!! There is no point 3 teams bug-fixxing and building the same thing in 3 different ways.

We aim for improvements, not perfection, otherwise nothing will ever ben submitted. For me, as this is a massive improvement (over what the style-guide has previously i.e. nothing), lets get it in, then if there are bugs, lets improve it.

**Comment by peter-mouland** [comment]
@rogerfranklin2 @bdo we have made the classes look like yours.  But we have prefixed them with `now-` instead of `sc-` and also ensured that the component use `layout-` in all classes. everything else is the same.

**Comment by andrewmerrell** [comment]
@peter-mouland agree with your sentiment otherwise I fear we'll end with more duplication as a result, we can contribute to collaborate and further perfect it once it is centralised, when it remains local to projects no one else can benefit.

Based on the last global catch up we decided this is something we want to do, so I suggest we centralise asap to align everyone, the longer we leave it the potential for complexity to switch increases and the duplication effort continues.

To @rogerfranklin2 @bdo point I agree whilst we currently have no CSS structure suggest we keep it agnostic for the time being, use the convention they created to minimise the impact, we will all have to update at a point when we choose a CSS style direction.

**Comment by peter-mouland** [comment]
@rogerfranklin2 @bdo @ldabiralai Are you guys able to update this PR with the fixes you mention?

**Comment by rogerfranklin2** [comment]
Working on it now

**Comment by peter-mouland** [comment]
👌

**Comment by nowarkdev** [comment]
@alexjfno1 :+1:

**Comment by bentidy** [comment]
Just a note on this one, need to discuss this with the designers as the my account guys have been told that they should be having a max-width on the centre content. Something to bring up next tuesday with jamie

@rogerfranklin2

**Pull request merged**
