### PR TITLE
JM|PD: Using background image with url-loader to grab svgs for header…

### PR DESCRIPTION
**Pull request by nowarkdev**
@james-maher , @PLAGR34GTT 
Use icons as classes

### CODE REVIEW

**Comment by peter-mouland** [comment]
are you able to take screenshots of 'before' and 'after' so i can see what has been done?
I had a look on the demo site but can not tell where the changes are...

**Comment by nowarkdev** [comment]
Right now the toolkit is referencing svg's directly using webpack, this makes being able to pass in a certain icon to a react component more difficult. By just being able to pass in a class name then we think this will make things simpler. There is a PR for the toolkit which is coming which will show this, but that is dependant on this. @james-maher @ariley90

**Comment by peter-mouland** [comment]
i reckon, if the style-guide has code, the docs should document and demo this.
Can you update the docs too?

Should the name of this pr change to something more specific to what this pr does like , `add new xx icon + update xx icon`?

**Comment by nowarkdev** [comment]
Closed to be solved by 2 new PRs around icons and headers

**Pull request closed without merging**
