### PR TITLE
AR|PT: Update all mention of grey to English spelling

### PR DESCRIPTION
**Pull request by nowarkdev**

### CODE REVIEW

**Comment by benstokoe** [comment]
Looks good 👍

**Comment by benstokoe** [comment]
We'll have to update the react toolkit of its using these colours

**Comment by johnsibly** [comment]
Looks good :+1:

**Comment by peter-mouland** [comment]
who is AR|PT?

**Comment by peter-mouland** [comment]
this is a breaking change and is now breaking the react-toolkit! :monkey_face:

**Pull request merged**
