### PR TITLE
NC|BDO : updated colour of information notification to light-blue

### PR DESCRIPTION
**Pull request by bentidy**

### CODE REVIEW

**Comment by nowarkdev** [comment]
@alexjfno1 @rob-howe :+1:

**Comment by peter-mouland** [comment]
:+1: 
but please don't do a release yet as the next release will have to be a Major (just been merging in breaking changes)

**Comment by bdo** [comment]
But should we merge now?

**Comment by peter-mouland** [comment]
go ahead and merge if you want... maybe push the version number to `v5.0.0-rc3`and release under that

**Comment by peter-mouland** [comment]
released under v5.0.0-rc3

**Pull request merged**
