### PR TITLE
AF: FINAL FINAL breakpoints and layout for assurance, billing & my ac…

### PR DESCRIPTION
**Pull request by alexflorisca**
## What this PR resolves
Breakpoints for Assurance, Billing and My Account 3 column layout.  Note that breakpoints will be different for other teams as they have different layouts!

Sat down with Jamie and Menaj and actually looked at how the apps behave at different screen sizes and adjusted the breakpoints accordingly. Before they were using finger in the air estimates and just looking at Sketch files so it was obviously going to be different in the browser - hence why they kept changing. I've been assured these won't change now, although they might add a breakpoint for changing the size of the typography on large screens later on.

### CODE REVIEW

**Comment by bentidy** [comment]
:+1:

@ldabiralai @nwc1991

**Comment by tomatau** [comment]
:+1:

looks great!

**Comment by peter-mouland** [comment]
guys, i think this is a massive breaking change... those mixins and variables are available externally.
They're definately being used in the react-toolkit and possibly elsewhere

**Comment by ldabiralai** [comment]
I'm not sure I agree with it being a massive breaking change. I can see where you coming from by saying it is one though, seeing as the look and feel changes a little bit.

But as this change does not affect how the consumers are using this, so I would argue that it's not actually a breaking change.

I don't believe anyone is using ```wide```, at least we're not in billing and @alexflorisca mentioned that assurance weren't either.

This shouldn't have any effect on padding/gutters in the grid. It could be a good idea to update the grid to use the same breakpoints as this though.

**Comment by peter-mouland** [comment]
ah, yeah - sorry, my bad. I could have sworn the toolkit relied on wide, but it doesn't.
massive breaking change was a bit of an overstatement 😅

**Pull request merged**
