### PR TITLE
Update typography

### LINKED ISSUE #135: Typography Update
The typography isn't currently up to date with the Zeplin Style-guide

When getting the 2 to match, It would be good to be able to also match our class names with the terms used in Zeplin ie have `n-primary-title` etc.

When making text in our apps bold, regular or light there are 2 ways we could go about this.  
 1. Adding a selector to our app's CSS to override the style-guide
 2. Or, adding a class to the HTML

I think method 1 would make our apps brittle and would prefer to be able to have classes that allow the text to change weight.  We could also create a class within the app itself but sometimes there is no repeatable reason or purpose why the weight changes.  Maybe the text just happens to be too long and the weight needs to be lowered.  For this reason, I think util classes from the style-guide makes more sense (i.e. `.n-light-text`, `n-bold-text`, n-regular-text`).

This update will probably be a breaking change and as such, should go into the next versions release candidate branch rather than into master.

@jamiehgreen would like to review in an app when this gets done.

### PR DESCRIPTION
**Pull request by tomatau**
fixes #135

## What this PR resolves
Adds utility classes for all default typography styles as well as the modifiers. Also adds examples in docs

## Screenshot after PR:

typography-table

### CODE REVIEW

**Comment by nowarkdev** [comment]
@roryp2 @PLAGR34GTT 

Looks good. Would be useful to mention what the old class names were  and what they map to, to help any one to update their apps that were using them.

:+1:

**Comment by devdpontes** [comment]
How about we create a change-log.md or migration.md file, instead of mentioning directly in the styleguide page? That way we can even track those changes.

**Comment by NowTV-Assurance** [comment]
Added the changelog.md with migrating instructions.

@devdpontes @tomatau

**Comment by nowarkdev** [comment]
Looks good :+1: 

@ldabiralai @yhzgirl

**Pull request merged**
