### PR TITLE
AN|RH: Added new colour buttons

### PR DESCRIPTION
**Pull request by nowarkdev**
Added new colour buttons, purple, orange, blue and pink and renamed <b>blue</b> to <b>dark-blue</b> to reflect the colours renamed in a recent PR.

### CODE REVIEW

**Comment by nowarkdev** [comment]
:+1:

**Comment by peter-mouland** [comment]
as discussed: maybe keep the secondary blue button to prevent the breaking change, and for now we'll say tweaking an existing colour is a 'bug fix'

**Comment by peter-mouland** [comment]
have you guys forgotten to keep the secondary blue in the demo?

**Comment by nowarkdev** [comment]
We have just added it to the examples.

**Comment by peter-mouland** [comment]
:+1:

**Pull request merged**
