### PR TITLE
refactor fonts to allow font-weight to determine which font is used

### PR DESCRIPTION
**Pull request by peter-mouland**
This means we no longer have to specify the font-family, only the font-weight.
Ie. if we want a bold font, use : 
```css
font-weight: bold
``` 
instead of using `@extends` or ... `font-family: nowtv-bold, helvetica, arial;font-weight: normal;`  which is allows fonts to look bold even when the font hasn't downloaded.

I have already removed the class `bolder-text` as it was the same as `nowtv-bold`.

It raises the question if the classes `nowtv-light`, `nowtv-regular` and `nowtv-bold` are needed at all?

### CODE REVIEW

**Comment by alexflorisca** [comment]
Not a big fan of using utility classes just to set the font-weight...but you already know that....Otherwise looks good :+1:

**Comment by peter-mouland** [comment]
ha ha - those classes already exist; before it made setting the font-weight look difficult (as the font-family also needed to be set)

**Comment by bdo** [comment]
Good pull request. 

_Might be nicer in the future to keep these pull requests small and to the point (adding margin to doc's titles was not necessary for this pull request). I know you're trying to save time, but the time each team spends to review the PR is increased._

:+1:

**Comment by peter-mouland** [comment]
yeah - sorry about. we saw the bug from the last merge and just tried to fix it... but would be best to stay on point!

**Pull request merged**
