### PR TITLE
Header desktop

### PR DESCRIPTION
**Pull request by nowarkdev**
This updates the header component to work in desktop based on the specs we have seen within the Sales designs but aren't yet available in the toolkit. 

We have been informed by our designer that the h1 styling in the style guide is incorrect and therefore we have updated the typography rather than add the styles just the to the .header-heading class.

@ariley90 @james-maher

### CODE REVIEW

**Comment by alexflorisca** [comment]
:+1:

**Comment by peter-mouland** [comment]
:+1: I'm not a fan of using extends (it creates hidden dependencies )
but I dont want to block this..  we should find out if there is a consensus about this

**Comment by nowarkdev** [comment]
@peter-mouland Yeah I wasn't sure but the other option was to take a copy of the rules and have them in 2 places. The main heading is tied to the h1 styles, the .larger-text style doesn't have a base element that is implementing it so extends felt like the best option.
@ariley90

**Comment by peter-mouland** [comment]
I think i'd go with saying the header class should sort out the margin/padding and the font size should be sorted by the typography class.  This would mean the html element would have 2 classes. i'm ok with that but feel i might be in the minority!

**Pull request merged**
