### PR TITLE
JM,AR: Added background color to input field as it was inheriting par…

### PR DESCRIPTION
**Pull request by nowarkdev**
Fix for input field - Added background colour to input field as it was inheriting parent background colour during validation check.

@james-maher

### CODE REVIEW

**Comment by alexflorisca** [comment]
:+1:

**Comment by peter-mouland** [comment]
:+1:

**Comment by nowarkdev** [comment]
@peter-mouland @alexflorisca Didn't realise this was :+1:'ed. Happy for the IE fix to be included? It removes the browsers X from the right handside of the input when either valid or error class is applied.

**Comment by alexflorisca** [comment]
Works for me.

**Comment by peter-mouland** [comment]
cool

**Pull request merged**
